name: Web â€“ Build & Deploy Frontend to Test Server

on:
  push:
    branches:
      - 'staging@web'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      DEPLOY_KEY: ${{ secrets.MARLIN_DEPLOY_KEY }}
      DEPLOY_PATH: ${{ secrets.MARLIN_FRONTEND_TEST_DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Build frontend artifacts
        run: npm run web:build:test

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.DEPLOY_KEY }}" > ~/.ssh/marlin_deploy_key
          chmod 600 ~/.ssh/marlin_deploy_key
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy build artifacts to test server
        run: |
          scp -i ~/.ssh/marlin_deploy_key -r dist/* ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOY_PATH }}